version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=*3dm7$$o83qo=)(m=7qg113)1^jxs!n%-9$$4i5k7m^20%89#=9y
      - DEBUG=1
      - SENDGRID_API_KEY=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
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: