# Generated by Django 3.0.5 on 2020-04-30 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.IntegerField()),
                ('page_length', models.IntegerField()),
                ('assigned_class', models.CharField(max_length=75)),
                ('subject', models.CharField(max_length=75)),
            ],
        ),
    ]
