# Generated by Django 3.0.5 on 2020-05-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='assigned_class',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
