# Generated by Django 3.0.5 on 2020-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
